# Generated by Django 4.0.4 on 2022-04-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collect_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectpoint',
            options={'verbose_name': 'Ponto'},
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
