# Generated by Django 4.0.4 on 2022-05-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_points', '0002_alter_collectpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpoint',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='logo_url',
            field=models.CharField(max_length=1024, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nome'),
        ),
    ]
