# Generated by Django 4.0.4 on 2022-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_points', '0003_alter_collectpoint_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpoint',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
