# Generated by Django 4.0.4 on 2022-05-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_points', '0004_alter_collectpoint_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectpoint',
            name='description',
        ),
    ]
