# Generated by Django 4.0.4 on 2022-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_points', '0005_remove_collectpoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectpoint',
            name='address',
            field=models.CharField(default='', max_length=512, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
